baseURL = '/'
languageCode = 'en-us'
title = 'Daragh Hollman'

theme = "anatole"
summaryLength = 30

[params]
title = "Daragh Hollman"
author = "Daragh Hollman"
description = """
Planetary Scientist
Programmer
Kayaker
"""
profilePicture = "images/profilePicture.jpg"
reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'
contentratio = 0.73
readMore = true
customCss = ["css/custom.css"]

    [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/daraghhollman/"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/daraghhollman/"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "e-mail"
    url = "mailto:dhollman@cp.dias.ie"

[menu]

    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Projects"
    weight = 300
    identifier = "projects"
    url = "/projects/"

    [[menu.main]]
    name = "Research"
    weight = 400
    identifier = "research"

        [[menu.main]]
        name = "Publications"
        weight = 410
        identifier = "publications"
        url = "/publications/"
        parent = "research"

        [[menu.main]]
        name = "Abstracts"
        weight = 420
        identifier = "abstracts"
        url = "/abstracts/"
        parent = "research"

        [[menu.main]]
        name = "Presentations"
        weight = 420
        identifier = "presentations"
        url = "/presentations/"
        parent = "research"

    [[menu.main]]
    name = "Gallery"
    weight = 500
    identifier = "gallery"
    url = "/gallery/"

    [[menu.main]]
    name = "Contact"
    weight = 600
    identifier = "contact"
    url = "/contact/"
